export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_COUNTRY_BY_NAME = "GET_COUNTRY_BY_NAME";
export const GET_COUNTRY_BY_REGION_NAME = "GET_COUNTRY_BY_REGION_NAME";
export const GET_COUNTRY_BY_SEARCH = "GET_COUNTRY_BY_SEARCH";
export const SET_LOADING = "SET_LOADING";
